name: SmartGreen CI/CD
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Versión actualizada 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Versión LTS más reciente
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Angular app
        run: npm run build -- --configuration=production