name: SmartGreen Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3     
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Usa una versión LTS de Node.js
          cache: 'npm'